services:
  - type: web
    name: kpiflow-frontend
    env: python
    plan: starter          # choose a paid plan so it never sleeps
    autoDeploy: true
    buildCommand: |
      pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/streamlit_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      # add any secrets you use in Streamlit here (e.g., OPENAI_API_KEY)
