services:
  # ---- Streamlit UI ----
  - type: web
    name: kpiflow-frontend
    region: oregon
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    previews: false
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      # Fill this after backend is live:
      - key: API_BASE_URL
        sync: false

  # ---- FastAPI API ----
  - type: web
    name: kpiflow-api
    region: oregon
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    autoDeploy: true
    previews: false
    healthCheckPath: /healthz
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      # Set this to the frontend URL after the first deploy
      - key: UI_ORIGIN
        sync: false
