services:
  - type: web
    name: kpiflow-frontend
    env: python
    plan: starter
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
    startCommand: >
      streamlit run frontend/app.py
      --server.address 0.0.0.0
      --server.port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
      - key: BACKEND_URL
        value: https://kpiflow-api-603131501793.us-central1.run.app
