services:
  - type: web
    name: kpiflow-frontend
    env: python
    plan: starter              # paid → always-on
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
    startCommand: >
      streamlit run frontend/streamlit_app.py
      --server.address 0.0.0.0
      --server.port $PORT
    envVars:
      - key: PYTHONPATH        # let frontend import from shared/
        value: .
      - key: BACKEND_URL       # your Cloud Run API (already hot)
        value: https://kpiflow-api-603131501793.us-central1.run.app
